repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2  # Use the desired version of Ruff
    hooks:
      # Run the linter with auto-fix enabled.
      - id: ruff
        args: ["--fix"]